version: '3'
services:
  k3s:
    # https://k3s.io
    image: rancher/k3s:v1.0.0
    command: server --node-name=k3s --no-deploy=traefik --no-deploy=servicelb
    privileged: true
    ports:
      - "6443:6443"
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/config
      - K3S_KUBECONFIG_MODE=666
    tmpfs:
      - /run
      - /var/run
    volumes:
      - ./.kube:/output

