apiVersion: route53.skpr.io/v1
kind: HealthCheck
metadata:
  name: healthcheck-sample
spec:
  name_prefix: pnx-prod
  domain: prod.pnx-d8.pnx.skpr.live
  port: 443
  type: HTTPS
  resource_path: /healthz?token=5n15oSNULeOfL1aIMPaLP7Y9
  alarm_actions:
    - arn:aws:sns:us-east-1:646598420362:HealthzAlerts
  ok_actions:
    - arn:aws:sns:us-east-1:646598420362:HealthzAlerts
