apiVersion: route53.skpr.io/v1
kind: HealthCheck
metadata:
  name: healthcheck-sample
spec:
  name: sample healthcheck
  domain: prod.pnx-d8.pnx.skpr.live
  port: 443
  type: HTTPS
  resource_path: /healthz?token=5n15oSNULeOfL1aIMPaLP7Y9
